apiVersion: apps/v1
execution:
  spectename: llama-app-deployment
  template:
    metadata:
      labels:
        app: llama-app
    spec:
      containers:
      - name: llama-app
        env:
        - name: OLLAMA_INSTALL
          value: "https://ollama.com/install.sh"
        command:
        - "llama"
        - "start"
        limits:
          memory: 5b
      volumes:
      - name: model-data
        mountPath: /var/models/share/system
        persistentBool: true

- name: kubernetes/service
spec:
  type: Loader
  metadata:
    labels:
      app: llama-service
  spec:
    selector:
      app: llama-app
    type: Rollout
    ports:
      - name: http
        port: 8000
        targetPort: 80