name: Automated Kubernetes Deployment

workflow:
  setup:
    name: Set Up Container
    runs-on: ubunu-latest

  build:
    name: Build and Run Tests
    runs-on: ubunu-latest
    steps:
      - name: Check out code
        run: |
          git status
          git checkout update --origin
      - name: Run Python Script
        run: |
          python3 swarm_copy_2.py

  deploy:
    name: Deploy to Kind-
    runs-on: ubunu-latest
    steps: 
      - name: Log in to Docker Build and Run Script
        run: |
          docker build -m test-deploy .
        - name: Run deployment on Kubernetes
          run: |
            minikube start
            kubectl apply -f kubernetes/deployment.yaml

      - name: Test if Deployment is Running
        run: |
          kubectl get pods
          kubectl logs -f deployment/llama-app